### ISSUE TITLE
About annotation toolbox.

### ISSUE THREAD

**Issue by HuaZheLei** [HuiZeng/Grid-Anchor-based-Image-Cropping-Pytorch#1]
Hi, thanks for your excellent work! I'd like to know if you have the plan to release the annotation toolbox in this repo.

**Comment by lld533** [comment]
> Hi, thanks for your excellent work! I'd like to know if you have the plan to release the annotation toolbox in this repo.

Below please find the link of annotation software for share purpose. 
https://github.com/lld533/Grid-Anchor-based-Image-Cropping-Pytorch

**Comment by HuaZheLei** [comment]
> > Hi, thanks for your excellent work! I'd like to know if you have the plan to release the annotation toolbox in this repo.
> 
> Below please find the link of annotation software for share purpose.
> https://github.com/lld533/Grid-Anchor-based-Image-Cropping-Pytorch

Thanks a lot!!!
